// CapiWebFrontEndAngular/src/app/pages/fileshare/components/file-preview-modal/file-preview-modal.component.ts
import { Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';

interface FileItem {
    id: number;
    filename: string;
    size: number;
    created_at: string;
    is_viewed: boolean;
}

@Component({
    selector: 'app-file-preview-modal',
    imports: [CommonModule],
    templateUrl: './file-preview-modal.component.html',
    styleUrls: ['../../fileshare.component.css'],
})
export class FilePreviewModalComponent {
    file = input.required<FileItem>();

    close = output<void>();
    download = output<{ id: number; filename: string }>();
    delete = output<number>();

    get isImage(): boolean {
        return /\.(jpg|jpeg|png|gif|webp)$/i.test(this.file().filename);
    }

    get downloadUrl(): string {
        return `http://localhost:8000/api/transfers/${this.file().id}/download/`;
    }

    onClose(): void {
        this.close.emit();
    }

    onDownload(): void {
        this.download.emit({ id: this.file().id, filename: this.file().filename });
    }

    onDelete(): void {
        this.delete.emit(this.file().id);
    }

    onOverlayClick(event: MouseEvent): void {
        if (event.target === event.currentTarget) {
            this.onClose();
        }
    }
}

<div class="modalOverlay" (click)="onOverlayClick($event)">
    <div class="modalContent" (click)="$event.stopPropagation()">
        <button class="closeModalBtn" (click)="onClose()">✕</button>

        <div class="previewHeader">
            <h3>{{ file().filename }}</h3>
            <div class="previewMeta">
                <span>{{ (file().size / 1024).toFixed(1) }} KB</span>
                <span class="separator">•</span>
                <span>{{ file().created_at | date: 'short' }}</span>
            </div>
        </div>

        <div class="previewBody">
            @if (isImage) {
            <img [src]="downloadUrl" [alt]="file().filename" class="modalImage" />
            } @else {
            <div class="genericPreview">
                <div class="genericIcon">📄</div>
                <p>No hay vista previa disponible</p>
            </div>
            }
        </div>

        <div class="previewFooter">
            <button class="deleteBtn" (click)="onDelete()">Eliminar</button>
            <button class="downloadBtn" (click)="onDownload()">Descargar</button>
        </div>
    </div>
</div>

// CapiWebFrontend/src/pages/fileshare/components/FilePreviewModal.jsx
import { motion, AnimatePresence } from 'framer-motion'
import styles from '../FileShare.module.css'

export default function FilePreviewModal({ file, onClose, onDownload, onDelete }) {
    if (!file) return null

    const isImage = /\.(jpg|jpeg|png|gif|webp)$/i.test(file.filename)
    const downloadUrl = `http://localhost:8000/api/transfers/${file.id}/download/`

    return (
        <AnimatePresence>
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className={styles.modalOverlay}
                onClick={onClose}
            >
                <motion.div
                    initial={{ scale: 0.9, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    exit={{ scale: 0.9, opacity: 0 }}
                    className={styles.modalContent}
                    onClick={(e) => e.stopPropagation()}
                >
                    <button className={styles.closeModalBtn} onClick={onClose}>✕</button>

                    <div className={styles.previewHeader}>
                        <h3>{file.filename}</h3>
                        <div className={styles.previewMeta}>
                            <span>{(file.size / 1024).toFixed(1)} KB</span>
                            <span className={styles.separator}>•</span>
                            <span>{new Date(file.created_at).toLocaleDateString()}</span>
                        </div>
                    </div>

                    <div className={styles.previewBody}>
                        {isImage ? (
                            <img src={downloadUrl} alt={file.filename} className={styles.modalImage} />
                        ) : (
                            <div className={styles.genericPreview}>
                                <div className={styles.genericIcon}>📄</div>
                                <p>No hay vista previa disponible</p>
                            </div>
                        )}
                    </div>

                    <div className={styles.previewFooter}>
                        <button
                            className={styles.deleteBtn}
                            onClick={() => onDelete(file.id)}
                        >
                            Eliminar
                        </button>
                        <button
                            className={styles.downloadBtn}
                            onClick={() => onDownload(file.id, file.filename)}
                        >
                            Descargar
                        </button>
                    </div>
                </motion.div>
            </motion.div>
        </AnimatePresence>
    )
}
