// CapiWebFrontEndAngular/src/app/pages/fileshare/components/file-upload/file-upload.component.ts
import { Component, input, output, signal, effect } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiClientService } from '../../../../services/api-client.service';

interface User {
    username: string;
    email?: string;
    is_staff?: boolean;
}

@Component({
    selector: 'app-file-upload',
    imports: [CommonModule, FormsModule],
    templateUrl: './file-upload.component.html',
    styleUrls: ['../../fileshare.component.css'],
})
export class FileUploadComponent {
    user = input.required<User | null>();
    selectedRecipient = input<string>('');

    uploadSuccess = output<void>();
    recipientChange = output<string>();

    file = signal<File | null>(null);
    recipient = signal('');
    description = signal('');
    uploading = signal(false);
    error = signal('');
    sendToSelf = signal(false);

    constructor(private apiClient: ApiClientService) {
        // Sync with selectedRecipient from parent
        effect(() => {
            const selected = this.selectedRecipient();
            const currentUser = this.user();
            if (selected) {
                this.recipient.set(selected);
                this.sendToSelf.set(selected === currentUser?.username);
            }
        });
    }

    handleFileChange(event: Event): void {
        const input = event.target as HTMLInputElement;
        if (input.files && input.files[0]) {
            this.file.set(input.files[0]);
        }
    }

    handleSelfToggle(event: Event): void {
        const checkbox = event.target as HTMLInputElement;
        const isChecked = checkbox.checked;
        this.sendToSelf.set(isChecked);

        if (isChecked && this.user()) {
            const username = this.user()!.username;
            this.recipient.set(username);
            this.recipientChange.emit(username);
        } else {
            this.recipient.set('');
            this.recipientChange.emit('');
        }
    }

    handleRecipientChange(value: string): void {
        this.recipient.set(value);
        this.recipientChange.emit(value);
        if (this.sendToSelf() && value !== this.user()?.username) {
            this.sendToSelf.set(false);
        }
    }

    async handleSubmit(event: Event): Promise<void> {
        event.preventDefault();
        if (!this.file() || !this.recipient()) return;

        this.uploading.set(true);
        this.error.set('');

        try {
            const formData = new FormData();
            formData.append('file', this.file()!);
            formData.append('recipient_username', this.recipient());
            if (this.description()) {
                formData.append('description', this.description());
            }

            await this.apiClient.uploadFile(formData);
            this.uploadSuccess.emit();

            // Reset form
            this.file.set(null);
            this.recipient.set('');
            this.description.set('');
            this.sendToSelf.set(false);
            this.recipientChange.emit('');

            // Reset file input
            const fileInput = document.querySelector(
                'input[type="file"]'
            ) as HTMLInputElement;
            if (fileInput) {
                fileInput.value = '';
            }
        } catch (err: any) {
            this.error.set(err.payload?.error || 'Error al subir archivo');
        } finally {
            this.uploading.set(false);
        }
    }
}

<div class="uploadContainer">
    <h2>Enviar Archivo</h2>
    <form (submit)="handleSubmit($event)" class="uploadForm">
        <div class="formGroup">
            <div class="recipientHeader">
                <label>Destinatario</label>
                <label class="checkboxLabel">
                    <input type="checkbox" [checked]="sendToSelf()" (change)="handleSelfToggle($event)" />
                    Enviarme a mí mismo
                </label>
            </div>
            <input type="text" [value]="recipient()" (input)="handleRecipientChange($any($event.target).value)"
                class="input" placeholder="Escribe el nombre de usuario..." required [disabled]="sendToSelf()" />
        </div>

        <div class="formGroup">
            <label>Archivo</label>
            <div class="fileInputWrapper">
                <input type="file" (change)="handleFileChange($event)" class="fileInput" required />
                <div class="fileDropZone">
                    {{ file() ? file()!.name : 'Arrastra un archivo o haz clic aquí' }}
                </div>
            </div>
        </div>

        <div class="formGroup">
            <label>Descripción (Opcional)</label>
            <textarea [value]="description()" (input)="description.set($any($event.target).value)" class="textarea"
                rows="3"></textarea>
        </div>

        @if (error()) {
        <p class="errorText">{{ error() }}</p>
        }

        <button type="submit" class="submitButton" [disabled]="uploading()">
            {{ uploading() ? 'Enviando...' : 'Enviar Archivo' }}
        </button>
    </form>
</div>

// CapiWebFrontend/src/pages/fileshare/components/FileUpload.jsx
import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import styles from '../FileShare.module.css'
import { apiClient } from '../../../services/apiClient'

export default function FileUpload({ onUploadSuccess, user, selectedRecipient, onRecipientChange }) {
    const [file, setFile] = useState(null)
    const [recipient, setRecipient] = useState('')
    const [description, setDescription] = useState('')
    const [uploading, setUploading] = useState(false)
    const [error, setError] = useState('')
    const [sendToSelf, setSendToSelf] = useState(false)

    // Sync with selectedRecipient from parent
    useEffect(() => {
        if (selectedRecipient) {
            setRecipient(selectedRecipient)
            setSendToSelf(selectedRecipient === user?.username)
        }
    }, [selectedRecipient, user])

    const handleFileChange = (e) => {
        if (e.target.files[0]) {
            setFile(e.target.files[0])
        }
    }

    const handleSelfToggle = (e) => {
        const isChecked = e.target.checked
        setSendToSelf(isChecked)
        if (isChecked && user) {
            setRecipient(user.username)
            if (onRecipientChange) {
                onRecipientChange(user.username)
            }
        } else {
            setRecipient('')
            if (onRecipientChange) {
                onRecipientChange('')
            }
        }
    }

    const handleRecipientChange = (value) => {
        setRecipient(value)
        if (onRecipientChange) {
            onRecipientChange(value)
        }
        if (sendToSelf && value !== user?.username) {
            setSendToSelf(false)
        }
    }

    const handleSubmit = async (e) => {
        e.preventDefault()
        if (!file || !recipient) return

        setUploading(true)
        setError('')

        try {
            const formData = new FormData()
            formData.append('file', file)
            formData.append('recipient_username', recipient)
            if (description) formData.append('description', description)

            await apiClient.uploadFile(formData)
            onUploadSuccess()
            // Reset form
            setFile(null)
            setRecipient('')
            setDescription('')
            setSendToSelf(false)
            if (onRecipientChange) {
                onRecipientChange('')
            }
        } catch (err) {
            setError(err.payload?.error || 'Error al subir archivo')
        } finally {
            setUploading(false)
        }
    }

    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className={styles.uploadContainer}
        >
            <h2>Enviar Archivo</h2>
            <form onSubmit={handleSubmit} className={styles.uploadForm}>
                <div className={styles.formGroup}>
                    <div className={styles.recipientHeader}>
                        <label>Destinatario</label>
                        <label className={styles.checkboxLabel}>
                            <input
                                type="checkbox"
                                checked={sendToSelf}
                                onChange={handleSelfToggle}
                            />
                            Enviarme a mí mismo
                        </label>
                    </div>
                    <input
                        type="text"
                        value={recipient}
                        onChange={(e) => handleRecipientChange(e.target.value)}
                        className={styles.input}
                        placeholder="Escribe el nombre de usuario..."
                        required
                        disabled={sendToSelf}
                    />
                </div>

                <div className={styles.formGroup}>
                    <label>Archivo</label>
                    <div className={styles.fileInputWrapper}>
                        <input
                            type="file"
                            onChange={handleFileChange}
                            className={styles.fileInput}
                            required
                        />
                        <div className={styles.fileDropZone}>
                            {file ? file.name : 'Arrastra un archivo o haz clic aquí'}
                        </div>
                    </div>
                </div>

                <div className={styles.formGroup}>
                    <label>Descripción (Opcional)</label>
                    <textarea
                        value={description}
                        onChange={(e) => setDescription(e.target.value)}
                        className={styles.textarea}
                        rows="3"
                    />
                </div>

                {error && <p className={styles.errorText}>{error}</p>}

                <button
                    type="submit"
                    className={styles.submitButton}
                    disabled={uploading}
                >
                    {uploading ? 'Enviando...' : 'Enviar Archivo'}
                </button>
            </form>
        </motion.div>
    )
}
