// CapiWebFrontEndAngular/src/app/pages/fileshare/components/notification-center/notification-center.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiClientService } from '../../../../services/api-client.service';

interface Notification {
    id: number;
    message: string;
    is_read: boolean;
}

interface FriendRequest {
    id: number;
    from_user_username: string;
}

@Component({
    selector: 'app-notification-center',
    imports: [CommonModule],
    templateUrl: './notification-center.component.html',
    styleUrls: ['../../fileshare.component.css'],
})
export class NotificationCenterComponent implements OnInit {
    notifications = signal<Notification[]>([]);
    requests = signal<FriendRequest[]>([]);
    isOpen = signal(false);

    constructor(private apiClient: ApiClientService) { }

    ngOnInit(): void { }

    async fetchData(): Promise<void> {
        try {
            const [notifsData, requestsData] = await Promise.all([
                this.apiClient.listNotifications(),
                this.apiClient.listFriendRequests(),
            ]);
            this.notifications.set(notifsData);
            this.requests.set(requestsData);
        } catch (error) {
            console.error('Error fetching notifications', error);
        }
    }

    toggleDropdown(): void {
        this.isOpen.update((v) => !v);
        if (this.isOpen()) {
            this.fetchData();
        }
    }

    async handleAccept(id: number): Promise<void> {
        try {
            await this.apiClient.acceptFriendRequest(id);
            this.fetchData();
        } catch (error) {
            console.error('Error accepting request', error);
        }
    }

    async handleReject(id: number): Promise<void> {
        try {
            await this.apiClient.rejectFriendRequest(id);
            this.fetchData();
        } catch (error) {
            console.error('Error rejecting request', error);
        }
    }

    get totalCount(): number {
        const unreadNotifs = Array.isArray(this.notifications())
            ? this.notifications().filter((n) => !n.is_read).length
            : 0;
        const pendingRequests = Array.isArray(this.requests())
            ? this.requests().length
            : 0;
        return unreadNotifs + pendingRequests;
    }
}

<div class="notificationCenter">
    <button class="bellButton" (click)="toggleDropdown()">
        🔔
        @if (totalCount > 0) {
        <span class="badge">{{ totalCount }}</span>
        }
    </button>

    @if (isOpen()) {
    <div class="dropdown">
        <h4>Solicitudes de Amistad</h4>
        @if (!requests() || requests().length === 0) {
        <p class="empty">No hay solicitudes pendientes</p>
        } @else {
        <ul class="notifList">
            @for (req of requests(); track req.id) {
            <li class="requestItem">
                <span>{{ req.from_user_username }} quiere ser tu amigo</span>
                <div class="requestActions">
                    <button (click)="handleAccept(req.id)" class="acceptBtn">✓</button>
                    <button (click)="handleReject(req.id)" class="rejectBtn">✕</button>
                </div>
            </li>
            }
        </ul>
        }

        <h4 style="margin-top: 1rem">Notificaciones</h4>
        @if (!notifications() || notifications().length === 0) {
        <p class="empty">No hay notificaciones</p>
        } @else {
        <ul class="notifList">
            @for (notif of notifications(); track notif.id) {
            <li class="notifItem" [class.unread]="!notif.is_read">
                {{ notif.message }}
            </li>
            }
        </ul>
        }
    </div>
    }
</div>

// CapiWebFrontend/src/pages/fileshare/components/NotificationCenter.jsx
import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import styles from '../FileShare.module.css'
import { apiClient } from '../../../services/apiClient'

export default function NotificationCenter() {
    const [notifications, setNotifications] = useState([])
    const [requests, setRequests] = useState([])
    const [isOpen, setIsOpen] = useState(false)

    useEffect(() => {
        if (isOpen) {
            fetchData()
        }
    }, [isOpen])

    const fetchData = async () => {
        try {
            const [notifsData, requestsData] = await Promise.all([
                apiClient.listNotifications(),
                apiClient.listFriendRequests()
            ])
            setNotifications(notifsData)
            setRequests(requestsData)
        } catch (error) {
            console.error('Error fetching notifications', error)
        }
    }

    const handleAccept = async (id) => {
        try {
            await apiClient.acceptFriendRequest(id)
            fetchData() // Refresh
        } catch (error) {
            console.error('Error accepting request', error)
        }
    }

    const handleReject = async (id) => {
        try {
            await apiClient.rejectFriendRequest(id)
            fetchData() // Refresh
        } catch (error) {
            console.error('Error rejecting request', error)
        }
    }

    const totalCount = (Array.isArray(notifications) ? notifications.filter(n => !n.is_read).length : 0) + (Array.isArray(requests) ? requests.length : 0)

    return (
        <div className={styles.notificationCenter}>
            <button
                className={styles.bellButton}
                onClick={() => setIsOpen(!isOpen)}
            >
                🔔
                {totalCount > 0 && (
                    <span className={styles.badge}>{totalCount}</span>
                )}
            </button>

            <AnimatePresence>
                {isOpen && (
                    <motion.div
                        className={styles.dropdown}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: 10 }}
                    >
                        <h4>Solicitudes de Amistad</h4>
                        {!Array.isArray(requests) || requests.length === 0 ? (
                            <p className={styles.empty}>No hay solicitudes pendientes</p>
                        ) : (
                            <ul className={styles.notifList}>
                                {requests.map(req => (
                                    <li key={req.id} className={styles.requestItem}>
                                        <span>{req.from_user_username} quiere ser tu amigo</span>
                                        <div className={styles.requestActions}>
                                            <button onClick={() => handleAccept(req.id)} className={styles.acceptBtn}>✓</button>
                                            <button onClick={() => handleReject(req.id)} className={styles.rejectBtn}>✕</button>
                                        </div>
                                    </li>
                                ))}
                            </ul>
                        )}

                        <h4 style={{ marginTop: '1rem' }}>Notificaciones</h4>
                        {!Array.isArray(notifications) || notifications.length === 0 ? (
                            <p className={styles.empty}>No hay notificaciones</p>
                        ) : (
                            <ul className={styles.notifList}>
                                {notifications.map(notif => (
                                    <li key={notif.id} className={`${styles.notifItem} ${!notif.is_read ? styles.unread : ''} `}>
                                        {notif.message}
                                    </li>
                                ))}
                            </ul>
                        )}
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    )
}
