// CapiWebFrontend/src/pages/auth/Auth.jsx
import { useState, useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { apiClient, ApiError } from '../../services/apiClient'
import styles from './Auth.module.css'

const TITLES = {
  login: {
    heading: 'Iniciar Sesión',
    subheading: 'Bienvenido de nuevo',
    button: 'Iniciar sesión',
    linkText: '¿No tienes cuenta?',
    linkHref: '/register',
    linkCta: 'Regístrate aquí',
  },
  register: {
    heading: 'Crear Cuenta',
    subheading: 'Únete a nosotros',
    button: 'Crear cuenta',
    linkText: '¿Ya tienes cuenta?',
    linkHref: '/login',
    linkCta: 'Inicia sesión aquí',
  },
}

export default function Auth({ mode = 'login', redirectPath = '/', title }) {
  const navigate = useNavigate()
  const meta = TITLES[mode]
  const displayTitle = title || meta.heading
  const [form, setForm] = useState({
    username: '',
    email: '',
    password: '',
    confirmPassword: '',
  })
  const [status, setStatus] = useState({ loading: false, error: '', success: '' })

  const passwordStrength = useMemo(() => calculatePasswordStrength(form.password), [form.password])

  const handleChange = (e) => {
    const { name, value } = e.target
    setForm((prev) => ({ ...prev, [name]: value }))
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    setStatus({ loading: true, error: '', success: '' })

    if (!form.username || !form.password) {
      setStatus((prev) => ({ ...prev, loading: false, error: 'Usuario y contraseña son obligatorios' }))
      return
    }

    if (mode === 'register') {
      if (form.password !== form.confirmPassword) {
        setStatus((prev) => ({ ...prev, loading: false, error: 'Las contraseñas no coinciden' }))
        return
      }
      if (form.password.length < 6) {
        setStatus((prev) => ({ ...prev, loading: false, error: 'La contraseña debe tener al menos 6 caracteres' }))
        return
      }
    }

    try {
      if (mode === 'login') {
        await apiClient.login({
          username: form.username.trim(),
          password: form.password,
        })
        setStatus({ loading: false, error: '', success: 'Inicio de sesión exitoso. Redirigiendo...' })
      } else {
        await apiClient.register({
          username: form.username.trim(),
          password: form.password,
          email: form.email.trim() || undefined,
        })
        setStatus({ loading: false, error: '', success: 'Registro exitoso. Redirigiendo...' })
      }

      setTimeout(() => navigate(redirectPath, { replace: true }), 600)
    } catch (error) {
      const message =
        error instanceof ApiError
          ? error.payload?.error || 'Credenciales inválidas'
          : 'Error de conexión. Intenta nuevamente.'
      setStatus({ loading: false, error: message, success: '' })
    }
  }

  return (
    <div className={styles.page}>
      <div className={styles.card}>
        <header className={styles.header}>
          <h1>{displayTitle}</h1>
          <p>{meta.subheading}</p>
        </header>

        {status.error ? <div className={styles.error}>{status.error}</div> : null}
        {status.success ? <div className={styles.success}>{status.success}</div> : null}

        <form className={styles.form} onSubmit={handleSubmit}>
          <div className={styles.formGroup}>
            <label htmlFor="username">Usuario</label>
            <input
              id="username"
              name="username"
              type="text"
              autoComplete="username"
              value={form.username}
              onChange={handleChange}
              required
            />
          </div>

          {mode === 'register' && (
            <div className={styles.formGroup}>
              <label htmlFor="email">Email (opcional)</label>
              <input
                id="email"
                name="email"
                type="email"
                autoComplete="email"
                value={form.email}
                onChange={handleChange}
              />
            </div>
          )}

          <div className={styles.formGroup}>
            <label htmlFor="password">Contraseña</label>
            <input
              id="password"
              name="password"
              type="password"
              autoComplete={mode === 'login' ? 'current-password' : 'new-password'}
              value={form.password}
              onChange={handleChange}
              required
            />
            {mode === 'register' && form.password ? (
              <>
                <div className={styles.strength}>
                  <div
                    className={styles.strengthBar}
                    data-strength={passwordStrength.level}
                    style={{ width: passwordStrength.width }}
                  />
                </div>
                <p className={styles[`strengthText-${passwordStrength.level}`]}>{passwordStrength.label}</p>
              </>
            ) : null}
          </div>

          {mode === 'register' && (
            <div className={styles.formGroup}>
              <label htmlFor="confirmPassword">Confirmar contraseña</label>
              <input
                id="confirmPassword"
                name="confirmPassword"
                type="password"
                autoComplete="new-password"
                value={form.confirmPassword}
                onChange={handleChange}
                required
              />
            </div>
          )}

          <button type="submit" className={styles.submit} disabled={status.loading}>
            {status.loading ? <span className={styles.loader} /> : meta.button}
          </button>
        </form>

        <div className={styles.divider}>
          <span>o</span>
        </div>

        <p className={styles.link}>
          {meta.linkText} <a href={meta.linkHref}>{meta.linkCta}</a>
        </p>
      </div>
    </div>
  )
}

function calculatePasswordStrength(password) {
  if (!password) {
    return { width: '0%', level: 'empty', label: '' }
  }
  let score = 0
  if (password.length >= 6) score++
  if (password.length >= 8) score++
  if (password.length >= 12) score++
  if (/[a-z]/.test(password) && /[A-Z]/.test(password)) score++
  if (/\d/.test(password)) score++
  if (/[^a-zA-Z\d]/.test(password)) score++

  if (score >= 5) return { width: '100%', level: 'strong', label: '🟢 Seguridad: Fuerte' }
  if (score >= 3) return { width: '66%', level: 'medium', label: '🟡 Seguridad: Media' }
  return { width: '33%', level: 'weak', label: '🔴 Seguridad: Débil' }
}

// CapiWebFrontEndAngular/src/app/pages/auth/auth.component.ts
import { Component, signal, computed, OnInit, Input } from '@angular/core';
import { Router, ActivatedRoute, RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiClientService } from '../../services/api-client.service';
import { ApiError } from '../../models/api-error';

interface AuthForm {
    username: string;
    email: string;
    password: string;
    confirmPassword: string;
}

interface PasswordStrength {
    width: string;
    level: 'empty' | 'weak' | 'medium' | 'strong';
    label: string;
}

@Component({
    selector: 'app-auth',
    imports: [CommonModule, FormsModule, RouterModule],
    templateUrl: './auth.component.html',
    styleUrl: './auth.component.css'
})
export class AuthComponent implements OnInit {
    @Input() set initialMode(value: 'login' | 'register') {
        this.mode.set(value);
    }
    @Input() redirectPath = '/';
    @Input() customTitle?: string;

    mode = signal<'login' | 'register'>('login');

    form = signal<AuthForm>({
        username: '',
        email: '',
        password: '',
        confirmPassword: ''
    });

    status = signal({
        loading: false,
        error: '',
        success: ''
    });

    passwordStrength = computed(() => this.calculatePasswordStrength(this.form().password));

    meta = computed(() => {
        const titles = {
            login: {
                heading: 'Iniciar Sesión',
                subheading: 'Bienvenido de nuevo',
                button: 'Iniciar sesión',
                linkText: '¿No tienes cuenta?',
                linkHref: '/register',
                linkCta: 'Regístrate aquí',
            },
            register: {
                heading: 'Crear Cuenta',
                subheading: 'Únete a nosotros',
                button: 'Crear cuenta',
                linkText: '¿Ya tienes cuenta?',
                linkHref: '/login',
                linkCta: 'Inicia sesión aquí',
            },
        };
        return titles[this.mode()];
    });

    displayTitle = computed(() => this.customTitle || this.meta().heading);

    constructor(
        private apiClient: ApiClientService,
        private router: Router,
        protected route: ActivatedRoute
    ) { }

    ngOnInit() {
        // Override in child components
    }

    goBack() {
        this.router.navigate(['/']);
    }

    updateForm(field: keyof AuthForm, value: string) {
        this.form.update(f => ({ ...f, [field]: value }));
    }

    async handleSubmit() {
        const formData = this.form();
        this.status.set({ loading: true, error: '', success: '' });

        if (!formData.username || !formData.password) {
            this.status.set({ loading: false, error: 'Usuario y contraseña son obligatorios', success: '' });
            return;
        }

        if (this.mode() === 'register') {
            if (formData.password !== formData.confirmPassword) {
                this.status.set({ loading: false, error: 'Las contraseñas no coinciden', success: '' });
                return;
            }
            if (formData.password.length < 6) {
                this.status.set({ loading: false, error: 'La contraseña debe tener al menos 6 caracteres', success: '' });
                return;
            }
        }

        try {
            if (this.mode() === 'login') {
                await this.apiClient.login({
                    username: formData.username.trim(),
                    password: formData.password,
                }).toPromise();
                this.status.set({ loading: false, error: '', success: 'Inicio de sesión exitoso. Redirigiendo...' });
            } else {
                await this.apiClient.register({
                    username: formData.username.trim(),
                    password: formData.password,
                    email: formData.email.trim() || undefined,
                }).toPromise();
                this.status.set({ loading: false, error: '', success: 'Registro exitoso. Redirigiendo...' });
            }

            setTimeout(() => this.router.navigate([this.redirectPath], { replaceUrl: true }), 600);
        } catch (error) {
            const message =
                error instanceof ApiError
                    ? error.payload?.error || 'Credenciales inválidas'
                    : 'Error de conexión. Intenta nuevamente.';
            this.status.set({ loading: false, error: message, success: '' });
        }
    }

    private calculatePasswordStrength(password: string): PasswordStrength {
        if (!password) {
            return { width: '0%', level: 'empty', label: '' };
        }
        let score = 0;
        if (password.length >= 6) score++;
        if (password.length >= 8) score++;
        if (password.length >= 12) score++;
        if (/[a-z]/.test(password) && /[A-Z]/.test(password)) score++;
        if (/\d/.test(password)) score++;
        if (/[^a-zA-Z\d]/.test(password)) score++;

        if (score >= 5) return { width: '100%', level: 'strong', label: '🟢 Seguridad: Fuerte' };
        if (score >= 3) return { width: '66%', level: 'medium', label: '🟡 Seguridad: Media' };
        return { width: '33%', level: 'weak', label: '🔴 Seguridad: Débil' };
    }
}

<div class="page">
    <button class="back-button" (click)="goBack()">
        ← Volver
    </button>
    <div class="card">
        <header class="header">
            <h1>{{ displayTitle() }}</h1>
            <p>{{ meta().subheading }}</p>
        </header>

        @if (status().error) {
        <div class="error">{{ status().error }}</div>
        }
        @if (status().success) {
        <div class="success">{{ status().success }}</div>
        }

        <form class="form" (ngSubmit)="handleSubmit()">
            <div class="formGroup">
                <label for="username">Usuario</label>
                <input id="username" name="username" type="text" autocomplete="username" [value]="form().username"
                    (input)="updateForm('username', $any($event.target).value)" required />
            </div>

            @if (mode() === 'register') {
            <div class="formGroup">
                <label for="email">Email (opcional)</label>
                <input id="email" name="email" type="email" autocomplete="email" [value]="form().email"
                    (input)="updateForm('email', $any($event.target).value)" />
            </div>
            }

            <div class="formGroup">
                <label for="password">Contraseña</label>
                <input id="password" name="password" type="password"
                    [autocomplete]="mode() === 'login' ? 'current-password' : 'new-password'" [value]="form().password"
                    (input)="updateForm('password', $any($event.target).value)" required />
                @if (mode() === 'register' && form().password) {
                <div class="strength">
                    <div class="strengthBar" [attr.data-strength]="passwordStrength().level"
                        [style.width]="passwordStrength().width"></div>
                </div>
                <p [class]="'strengthText-' + passwordStrength().level">{{ passwordStrength().label }}</p>
                }
            </div>

            @if (mode() === 'register') {
            <div class="formGroup">
                <label for="confirmPassword">Confirmar contraseña</label>
                <input id="confirmPassword" name="confirmPassword" type="password" autocomplete="new-password"
                    [value]="form().confirmPassword" (input)="updateForm('confirmPassword', $any($event.target).value)"
                    required />
            </div>
            }

            <button type="submit" class="submit" [disabled]="status().loading">
                @if (status().loading) {
                <span class="loader"></span>
                } @else {
                {{ meta().button }}
                }
            </button>
        </form>

        <div class="divider">
            <span>o</span>
        </div>

        <p class="link">
            {{ meta().linkText }} <a [routerLink]="meta().linkHref">{{ meta().linkCta }}</a>
        </p>
    </div>
</div>
