// CapiWebFrontend/src/pages/fileshare/components/FriendList.jsx
import { useState, useEffect, useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import styles from '../FileShare.module.css'
import { apiClient } from '../../../services/apiClient'
import { toast } from 'react-toastify'

export default function FriendList({ onSelectFriend }) {
    const [friends, setFriends] = useState([])
    const [newFriend, setNewFriend] = useState('')
    const [loading, setLoading] = useState(false)
    const [searchResults, setSearchResults] = useState([])
    const [showDropdown, setShowDropdown] = useState(false)
    const [searching, setSearching] = useState(false)
    const dropdownRef = useRef(null)
    const searchTimeout = useRef(null)

    useEffect(() => {
        fetchFriends()
    }, [])

    // Close dropdown when clicking outside
    useEffect(() => {
        const handleClickOutside = (event) => {
            if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
                setShowDropdown(false)
            }
        }
        document.addEventListener('mousedown', handleClickOutside)
        return () => document.removeEventListener('mousedown', handleClickOutside)
    }, [])

    // Debounced search
    useEffect(() => {
        if (searchTimeout.current) {
            clearTimeout(searchTimeout.current)
        }

        if (newFriend.trim().length > 0) {
            setSearching(true)
            searchTimeout.current = setTimeout(async () => {
                try {
                    const results = await apiClient.searchUsers(newFriend.trim())
                    setSearchResults(results)
                    setShowDropdown(true)
                } catch (error) {
                    console.error('Search error:', error)
                    setSearchResults([])
                } finally {
                    setSearching(false)
                }
            }, 300)
        } else {
            setSearchResults([])
            setShowDropdown(false)
            setSearching(false)
        }

        return () => {
            if (searchTimeout.current) {
                clearTimeout(searchTimeout.current)
            }
        }
    }, [newFriend])

    const fetchFriends = async () => {
        try {
            const data = await apiClient.listFriends()
            setFriends(data)
        } catch (error) {
            console.error('Error fetching friends', error)
        }
    }

    const handleAddFriend = async (username) => {
        setLoading(true)
        const loadingToast = toast.info(`Enviando solicitud a ${username}...`, {
            autoClose: false,
        })

        try {
            await apiClient.sendFriendRequest(username)
            toast.update(loadingToast, {
                render: 'Solicitud enviada correctamente',
                type: 'success',
                autoClose: 2000,
            })
            setNewFriend('')
            setShowDropdown(false)
            setSearchResults([])
        } catch (err) {
            const errorMsg = err.payload?.error || 'Error al enviar solicitud'
            toast.update(loadingToast, {
                render: errorMsg,
                type: 'error',
                autoClose: 3000,
            })
        } finally {
            setLoading(false)
        }
    }

    const handleSelectUser = (username) => {
        handleAddFriend(username)
    }

    const handleSelectFriend = (username) => {
        if (onSelectFriend) {
            onSelectFriend(username)
            toast.success(`${username} seleccionado para enviar archivo`, {
                autoClose: 2000,
            })
        }
    }

    const handleRemoveFriend = (username) => {
        const confirmToast = toast.warning(
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                <div style={{ fontWeight: 'bold', fontSize: '15px' }}>
                    ¿Eliminar a {username}?
                </div>
                <div style={{ fontSize: '13px', opacity: 0.9 }}>
                    Esta acción no se puede deshacer
                </div>
                <div style={{ display: 'flex', gap: '8px', marginTop: '8px' }}>
                    <button
                        onClick={() => {
                            toast.dismiss(confirmToast)
                            performRemoveFriend(username)
                        }}
                        style={{
                            flex: 1,
                            padding: '8px 16px',
                            background: 'linear-gradient(135deg, #FF3366 0%, #CC0044 100%)',
                            border: 'none',
                            borderRadius: '6px',
                            color: 'white',
                            fontWeight: 'bold',
                            cursor: 'pointer',
                            fontSize: '13px'
                        }}
                    >
                        Eliminar
                    </button>
                    <button
                        onClick={() => toast.dismiss(confirmToast)}
                        style={{
                            flex: 1,
                            padding: '8px 16px',
                            background: 'rgba(255, 255, 255, 0.1)',
                            border: '1px solid rgba(255, 255, 255, 0.2)',
                            borderRadius: '6px',
                            color: 'white',
                            cursor: 'pointer',
                            fontSize: '13px'
                        }}
                    >
                        Cancelar
                    </button>
                </div>
            </div>,
            {
                autoClose: false,
                closeButton: false,
                draggable: false,
                closeOnClick: false,
            }
        )
    }

    const performRemoveFriend = async (username) => {
        const loadingToast = toast.info('Eliminando amigo...', {
            autoClose: false,
        })

        try {
            await apiClient.removeFriend(username)
            toast.update(loadingToast, {
                render: 'Amigo eliminado correctamente',
                type: 'success',
                autoClose: 2000,
            })
            await fetchFriends()
        } catch (error) {
            console.error('Remove friend error:', error)
            toast.update(loadingToast, {
                render: 'Error al eliminar amigo',
                type: 'error',
                autoClose: 3000,
            })
        }
    }

    return (
        <div className={styles.friendList}>
            <h3>Amigos</h3>

            <div className={styles.addFriendForm} ref={dropdownRef}>
                <input
                    type="text"
                    value={newFriend}
                    onChange={(e) => setNewFriend(e.target.value)}
                    placeholder="Buscar usuario..."
                    className={styles.input}
                    disabled={loading}
                />

                <AnimatePresence>
                    {showDropdown && searchResults.length > 0 && (
                        <motion.div
                            initial={{ opacity: 0, y: -10 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -10 }}
                            className={styles.autocompleteDropdown}
                        >
                            {searchResults.map((user) => (
                                <motion.div
                                    key={user.id}
                                    className={styles.autocompleteItem}
                                    onClick={() => handleSelectUser(user.username)}
                                    whileHover={{ backgroundColor: 'rgba(0, 242, 255, 0.1)' }}
                                >
                                    <div className={styles.autocompleteAvatar}>
                                        {user.username[0].toUpperCase()}
                                    </div>
                                    <span>{user.username}</span>
                                </motion.div>
                            ))}
                        </motion.div>
                    )}
                </AnimatePresence>

                {searching && (
                    <div className={styles.searchingIndicator}>
                        Buscando...
                    </div>
                )}

                {showDropdown && !searching && searchResults.length === 0 && newFriend.trim().length > 0 && (
                    <div className={styles.noResults}>
                        No se encontraron usuarios
                    </div>
                )}
            </div>

            <ul className={styles.list}>
                {friends.length === 0 ? (
                    <li className={styles.emptyText}>No tienes amigos aún</li>
                ) : (
                    friends.map(friend => (
                        <motion.li
                            key={friend.id}
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            className={styles.friendItem}
                        >
                            <div className={styles.friendInfo}>
                                <div className={styles.avatar}>{friend.username[0].toUpperCase()}</div>
                                <span>{friend.username}</span>
                            </div>
                            <div className={styles.friendActions}>
                                <button
                                    className={styles.selectBtn}
                                    onClick={() => handleSelectFriend(friend.username)}
                                    title="Seleccionar para enviar archivo"
                                >
                                    📤
                                </button>
                                <button
                                    className={styles.removeBtn}
                                    onClick={() => handleRemoveFriend(friend.username)}
                                    title="Eliminar amigo"
                                >
                                    🗑️
                                </button>
                            </div>
                        </motion.li>
                    ))
                )}
            </ul>
        </div>
    )
}

// CapiWebFrontEndAngular/src/app/pages/fileshare/components/friend-list/friend-list.component.ts
import {
    Component,
    OnInit,
    OnDestroy,
    output,
    signal,
    effect,
    ElementRef,
    ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiClientService } from '../../../../services/api-client.service';
import { ToastrService } from 'ngx-toastr';
import { Subject, debounceTime, distinctUntilChanged } from 'rxjs';

interface Friend {
    id: number;
    username: string;
}

interface SearchUser {
    id: number;
    username: string;
}

@Component({
    selector: 'app-friend-list',
    imports: [CommonModule, FormsModule],
    templateUrl: './friend-list.component.html',
    styleUrls: ['../../fileshare.component.css'],
})
export class FriendListComponent implements OnInit, OnDestroy {
    @ViewChild('dropdownRef') dropdownRef?: ElementRef;

    selectFriend = output<string>();

    friends = signal<Friend[]>([]);
    newFriend = signal('');
    loading = signal(false);
    searchResults = signal<SearchUser[]>([]);
    showDropdown = signal(false);
    searching = signal(false);

    private searchSubject = new Subject<string>();
    private clickListener?: (event: MouseEvent) => void;

    constructor(
        private apiClient: ApiClientService,
        private toastr: ToastrService
    ) {
        // Setup debounced search
        this.searchSubject
            .pipe(debounceTime(300), distinctUntilChanged())
            .subscribe(async (searchTerm) => {
                if (searchTerm.trim().length > 0) {
                    this.searching.set(true);
                    try {
                        const results = await this.apiClient.searchUsers(searchTerm.trim());
                        this.searchResults.set(results);
                        this.showDropdown.set(true);
                    } catch (error) {
                        console.error('Search error:', error);
                        this.searchResults.set([]);
                    } finally {
                        this.searching.set(false);
                    }
                } else {
                    this.searchResults.set([]);
                    this.showDropdown.set(false);
                    this.searching.set(false);
                }
            });
    }

    ngOnInit(): void {
        this.fetchFriends();
        this.setupClickOutsideListener();
    }

    ngOnDestroy(): void {
        this.searchSubject.complete();
        if (this.clickListener) {
            document.removeEventListener('mousedown', this.clickListener);
        }
    }

    setupClickOutsideListener(): void {
        this.clickListener = (event: MouseEvent) => {
            if (
                this.dropdownRef &&
                !this.dropdownRef.nativeElement.contains(event.target)
            ) {
                this.showDropdown.set(false);
            }
        };
        document.addEventListener('mousedown', this.clickListener);
    }

    onSearchChange(value: string): void {
        this.newFriend.set(value);
        this.searchSubject.next(value);
    }

    async fetchFriends(): Promise<void> {
        try {
            const data = await this.apiClient.listFriends();
            this.friends.set(data);
        } catch (error) {
            console.error('Error fetching friends', error);
        }
    }

    async handleAddFriend(username: string): Promise<void> {
        this.loading.set(true);
        const loadingToast = this.toastr.info(
            `Enviando solicitud a ${username}...`,
            '',
            { disableTimeOut: true }
        );

        try {
            await this.apiClient.sendFriendRequest(username);
            this.toastr.clear(loadingToast.toastId);
            this.toastr.success('Solicitud enviada correctamente');
            this.newFriend.set('');
            this.showDropdown.set(false);
            this.searchResults.set([]);
        } catch (err: any) {
            const errorMsg = err.payload?.error || 'Error al enviar solicitud';
            this.toastr.clear(loadingToast.toastId);
            this.toastr.error(errorMsg);
        } finally {
            this.loading.set(false);
        }
    }

    handleSelectUser(username: string): void {
        this.handleAddFriend(username);
    }

    handleSelectFriend(username: string): void {
        this.selectFriend.emit(username);
        this.toastr.success(`${username} seleccionado para enviar archivo`);
    }

    handleRemoveFriend(username: string): void {
        const toastRef = this.toastr.warning(
            `
      <div style="display: flex; flex-direction: column; gap: 12px;">
        <div style="font-weight: bold; font-size: 15px;">¿Eliminar a ${username}?</div>
        <div style="font-size: 13px; opacity: 0.9;">Esta acción no se puede deshacer</div>
        <div style="display: flex; gap: 8px; margin-top: 8px;">
          <button id="confirm-remove-${username}" style="flex: 1; padding: 8px 16px; background: linear-gradient(135deg, #FF3366 0%, #CC0044 100%); border: none; border-radius: 6px; color: white; font-weight: bold; cursor: pointer; font-size: 13px;">Eliminar</button>
          <button id="cancel-remove-${username}" style="flex: 1; padding: 8px 16px; background: rgba(255, 255, 255, 0.1); border: 1px solid rgba(255, 255, 255, 0.2); border-radius: 6px; color: white; cursor: pointer; font-size: 13px;">Cancelar</button>
        </div>
      </div>
    `,
            '',
            {
                disableTimeOut: true,
                closeButton: false,
                enableHtml: true,
            }
        );

        setTimeout(() => {
            const confirmBtn = document.getElementById(`confirm-remove-${username}`);
            const cancelBtn = document.getElementById(`cancel-remove-${username}`);

            if (confirmBtn) {
                confirmBtn.onclick = () => {
                    this.toastr.clear(toastRef.toastId);
                    this.performRemoveFriend(username);
                };
            }

            if (cancelBtn) {
                cancelBtn.onclick = () => {
                    this.toastr.clear(toastRef.toastId);
                };
            }
        }, 100);
    }

    async performRemoveFriend(username: string): Promise<void> {
        const loadingToast = this.toastr.info('Eliminando amigo...', '', {
            disableTimeOut: true,
        });

        try {
            await this.apiClient.removeFriend(username);
            this.toastr.clear(loadingToast.toastId);
            this.toastr.success('Amigo eliminado correctamente');
            await this.fetchFriends();
        } catch (error) {
            console.error('Remove friend error:', error);
            this.toastr.clear(loadingToast.toastId);
            this.toastr.error('Error al eliminar amigo');
        }
    }
}

<div class="friendList">
    <h3>Amigos</h3>

    <div class="addFriendForm" #dropdownRef>
        <input type="text" [value]="newFriend()" (input)="onSearchChange($any($event.target).value)"
            placeholder="Buscar usuario..." class="input" [disabled]="loading()" />

        @if (showDropdown() && searchResults().length > 0) {
        <div class="autocompleteDropdown">
            @for (user of searchResults(); track user.id) {
            <div class="autocompleteItem" (click)="handleSelectUser(user.username)">
                <div class="autocompleteAvatar">{{ user.username[0].toUpperCase() }}</div>
                <span>{{ user.username }}</span>
            </div>
            }
        </div>
        }

        @if (searching()) {
        <div class="searchingIndicator">Buscando...</div>
        }

        @if (showDropdown() && !searching() && searchResults().length === 0 && newFriend().trim().length > 0) {
        <div class="noResults">No se encontraron usuarios</div>
        }
    </div>

    <ul class="list">
        @if (friends().length === 0) {
        <li class="emptyText">No tienes amigos aún</li>
        } @else {
        @for (friend of friends(); track friend.id) {
        <li class="friendItem">
            <div class="friendInfo">
                <div class="avatar">{{ friend.username[0].toUpperCase() }}</div>
                <span>{{ friend.username }}</span>
            </div>
            <div class="friendActions">
                <button class="selectBtn" (click)="handleSelectFriend(friend.username)"
                    title="Seleccionar para enviar archivo">
                    📤
                </button>
                <button class="removeBtn" (click)="handleRemoveFriend(friend.username)" title="Eliminar amigo">
                    🗑️
                </button>
            </div>
        </li>
        }
        }
    </ul>
</div>
